version: '3'
services:
  master:
    image: "redis"
    container_name: "redis_master"
    ports:
     - "63791:6379"
    volumes:
     - ./master.conf:/usr/local/etc/redis/redis.conf
     - ./data/master:/data
    command: redis-server /usr/local/etc/redis/redis.conf 
    privileged: true
  slave1:
    image: "redis"
    container_name: "redis_slave1"
    ports:
     - "63792:6379"
    volumes:
     - ./slave1.conf:/usr/local/etc/redis/redis.conf
     - ./data/slave1:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    privileged: true 
  slave2:
    image: "redis"
    container_name: "redis_slave2"
    ports:
     - "63793:6379"
    volumes:
     - ./slave2.conf:/usr/local/etc/redis/redis.conf
     - ./data/slave2:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    privileged: true