global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: kafka-consumer-monitor
    static_configs:
      - targets: ["192.168.1.8:8000"]
        labels:
          instance: localhost

  - job_name: prometheus
    static_configs:
      - targets: ["192.168.1.8:9090"]
        labels:
          instance: prometheus

  - job_name: "jaeger-metrics"
    static_configs:
      - targets: ["192.168.1.8:14269"]
        labels:
          instance: jaeger-metrics

  - job_name: linux
    static_configs:
      - targets: ["192.168.1.8:9100"]
        labels:
          instance: localhost
